#spring.jpa.generate-ddl=true
#spring.datasource.url=${JDBC_DATASOURCE_URL}
#spring.jpa.show-sql=true
spring:
  datasource:
    url: jdbc:${MYSQL_URL}
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true